
services:
  backend:
    build:
      context: ./backend
    container_name: mern-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mern-network
    env_file:
      - ./backend/.env
    

  frontend:
    build:
      context: ./frontend
    container_name: mern-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-network
    depends_on:
      - backend

networks:
  mern-network:
    driver: bridge

